=== isonovio/wyndis-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["impact"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/events/2023-08-12--esl-impact-cashcup-eu-2023-summer-4.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-summer-4",
    "name": "ESL Impact Cash Cup: Europe - Summer 2023 #4",
    "duration": { "start": "2023-08-12", "end": "2023-08-12" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Summer/4" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/c497b599-4203-4bfc-b65b-af8b2d29073e" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7351/esl-impact-summer-2023-cash-cup-4-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 3,
                    "date": "2023-08-12",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Let Her Cook" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-30f7d9ad-dcf0-442d-b733-cc3b921be91a" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "11:16" }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2023-07-29--cct-s1-eu-e-s1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "cct-s1-eu-e-s1",
    "name": "CCT Season 1 East Europe Series #1",
    "duration": { "start": "2023-07-29", "end": "2023-08-20" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/CCT/Season_1/East_Europe/Series_1" },
        { "name": "CCT", "url": "https://cctour.gg/tournaments/cct-east-europe" },
        { "name": "Rules", "url": "https://docs.google.com/document/d/1fTQRUN0IR9Q9bEhyI35for61D7J7k1gRLQG22zk-l78/edit" }
    ],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-2" } }],
    "brackets": [
        {
            "slug": "s2",
            "name": "Closed Q.",
            "links": [{ "name": "L.p.", "url": "https://liquipedia.net/counterstrike/CCT/Season_1/East_Europe/Series_1/Qualifier" }],
            "brackets": [
                {
                    "slug": "s1--group-stage",
                    "brackets": [
                        {
                            "slug": "gc",
                            "name": "Group C",
                            "matches": [
                                {
                                    "id": 2,
                                    "name": "Opening Match 2",
                                    "date": "2023-08-03",
                                    "lineups": { "team1": { "name": "Natus Vincere Youth" }, "team2": { "shorthand": "nipi" } },
                                    "links": [{ "name": "Bo3.gg", "url": "https://bo3.gg/matches/navi-youth-vs-ninjas-in-pyjamas-female-03-08-2023" }],
                                    "maps": [
                                        { "id": 1, "map": "mrg", "result": "16:3" },
                                        { "id": 2, "map": "ovp", "result": "16:10" }
                                    ]
                                },
                                {
                                    "id": 4,
                                    "name": "Elimination Match",
                                    "date": "2023-08-04",
                                    "lineups": { "team1": { "name": "BALLIST" }, "team2": { "shorthand": "nipi" } },
                                    "maps": [],
                                    "note": "BALLIST forfeited the match."
                                },
                                {
                                    "id": 1,
                                    "name": "Decider Match",
                                    "date": "2023-08-04",
                                    "lineups": { "team1": { "name": "Singularity" }, "team2": { "shorthand": "nipi" } },
                                    "links": [{ "name": "Bo3.gg", "url": "https://bo3.gg/matches/singularity-cs-go-vs-ninjas-in-pyjamas-female-04-08-2023" }],
                                    "maps": [
                                        { "id": 1, "map": "nuke", "result": "16:11" },
                                        { "id": 2, "map": "ovp", "result": "16:1" }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-10-01--npf-2022.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "npf-2022-semipro",
    "name": "NPF 2022 Semi Pro",
    "duration": { "start": "2022-10-14", "end": "2022-10-15" },
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2", "coach": "rookie" } }],
    "brackets": [
        {
            "slug": "s1--group-play",
            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/championship/2e8873a4-966e-4274-ae8e-3a92c224d941" }],
            "brackets": [
                {
                    "slug": "gg",
                    "name": "Group G",
                    "matches": [
                        {
                            "id": 1,
                            "date": "2022-10-14",
                            "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Kalokiokuglerne" } },
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-e89aeeae-948d-4eab-816f-afe44b91a77e" }],
                            "maps": [{ "id": 1, "map": "vtg", "result": "4:16" }]
                        },
                        {
                            "id": 2,
                            "date": "2022-10-14",
                            "lineups": { "team1": { "name": "vamoss" }, "team2": { "shorthand": "cfs" } },
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-3896be68-8110-41b6-bf8d-13c43a042d69" }],
                            "maps": [{ "id": 1, "map": "vtg", "result": "16:3" }]
                        },
                        {
                            "id": 3,
                            "date": "2022-10-14",
                            "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "KES-Eagles" } },
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-ce6f8474-4725-4f8c-931f-55488b5ac19e" }],
                            "maps": [{ "id": 1, "map": "ovp", "result": "16:5" }]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2020-05-01--faceit-loyalty-2020-05-01.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "faceit-loyalty-2020-05-01",
    "name": "FACEIT Loyalty Series 2020-05-01",
    "duration": { "start": "2020-05-01", "end": "2020-05-01" },
    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/championship/bc42499b-8e9c-475b-8ce6-80bab70fbf06" }],
    "participants": [{ "shorthand": "n", "lineup": { "name": "ExitLife", "players": ["nayomy"] } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 2,
                    "date": "2020-05-01",
                    "lineups": { "team1": { "shorthand": "n" }, "team2": { "name": "Team cheapicetea" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-c40fe57e-2dd8-4026-9ae0-6891bf991514" }],
                    "maps": [{ "id": 1, "map": "inf", "result": "19:17" }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Quarterfinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2020-05-01",
                    "lineups": { "team1": { "name": "NotCheatsBro" }, "team2": { "shorthand": "n" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-6865c83b-abd5-4e99-9178-09da344b9bcb" }],
                    "maps": [{ "id": 1, "map": "mrg", "result": "6:16" }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2023-04-22--esl-impact-cashcup-eu-2023-spring-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-spring-2",
    "name": "ESL Impact Cash Cup: Europe - Spring 2023 #2",
    "duration": { "start": "2023-04-22", "end": "2023-04-23" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Spring/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2422" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2422" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7173/esl-impact-spring-2023-cash-cup-2-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 4,
                    "date": "2023-04-22",
                    "lineups": { "team1": { "name": "Larance" }, "team2": { "shorthand": "nipi" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "5:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053593" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 2,
                    "date": "2023-04-22",
                    "lineups": { "team1": { "team": "cfs" }, "team2": { "shorthand": "nipi" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "4:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053635" }] },
                        { "id": 2, "map": "ovp", "result": "11:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053661" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-04-23",
                    "lineups": { "team1": { "name": "NAVI Javelins" }, "team2": { "shorthand": "nipi" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2363935/navi-javelins-vs-nip-impact-esl-impact-spring-2023-cash-cup-2-europe" }],
                    "maps": [
                        { "id": 1, "map": "inf", "result": "1:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053774" }] },
                        { "id": 2, "map": "anc", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053780" }] },
                        { "id": 3, "map": "mrg", "result": "16:9", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17053787" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2021-04-10--girlgamer-challenge-eu.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "girlgamer-challenge-eu",
    "name": "GIRLGAMER Challenge Europe",
    "duration": { "start": "2021-04-10", "end": "2021-04-25" },
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-1" } }],
    "brackets": [
        {
            "slug": "s1--qualifers",
            "brackets": [
                {
                    "slug": "q1",
                    "name": "Qualifier 1",
                    "matches": [
                        {
                            "id": 1,
                            "date": "2021-04-10",
                            "lineups": { "team1": { "name": "HyperspaceGirls" }, "team2": { "shorthand": "nsc" } },
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-8c7b1cb9-48f1-49f3-8a1c-fa0a14937c6d" }],
                            "maps": [
                                { "id": 1, "map": "ovp", "result": "16:13" },
                                { "id": 2, "map": "d2", "result": "11:16" },
                                { "id": 3, "map": "nuke", "result": "8:16" }
                            ]
                        },
                        {
                            "id": 2,
                            "date": "2021-04-10",
                            "lineups": { "team1": { "name": "Arcane Wave" }, "team2": { "shorthand": "nsc" } },
                            "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-d664a21c-e655-4b95-9b3e-6abc890eb8c0" }],
                            "maps": [
                                { "id": 1, "map": "trn", "result": "16:6" },
                                { "id": 2, "map": "inf", "result": "14:16" },
                                { "id": 3, "map": "d2", "result": "19:16" }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-01-15--esea-fe-cashcup-eu-2022-winter-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esea-fe-cashcup-eu-2022-winter-1",
    "name": "ESEA Female Cash Cup: Europe - Winter 2022 #1",
    "duration": { "start": "2022-01-15", "end": "2022-01-16" },
    "links": [
        { "name": "Liquipedia", "url": "https://liquipedia.net/counterstrike/ESEA/Cash_Cup/Female/Europe/2022/Winter/1" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1297" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1297" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6356/esea-winter-2021-women-cash-cup-1-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round 1",
            "matches": [
                {
                    "id": 4,
                    "date": "2022-01-15",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "proklyatie" } },
                    "maps": [{ "id": 1, "map": "vtg", "result": "16:1", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16832960" }] }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 6,
                    "date": "2022-01-15",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "equipa" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "11:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16833022" }] }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2026-07-06--esports-nations-cup-2026.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esports-nations-cup-2026",
    "name": "Esports Nations Cup 2026",
    "duration": { "start": "2026-07-06", "end": "2026-11-15" },
    "links": [
        { "name": "ENC", "url": "https://esportsnationscup.com/en/competitions/2026/cs2" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/Esports_Nations_Cup/2026" }
    ],
    "participants": [{ "shorthand": "kna", "lineup": { "name": "Kan niet anders", "players": ["d0cc", "kd69z", "nayomy", "neok", "qiyarah"] } }],
    "brackets": [
        {
            "slug": "s1--national-qualifers",
            "duration": { "start": "2026-07-06", "end": "2026-07-16" },
            "brackets": [
                {
                    "slug": "nl",
                    "name": "Netherlands Qualifier",
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/championship/0fcad12f-c05d-45ad-bde0-e4a2e85246a4" }],
                    "brackets": [
                        {
                            "slug": "r1",
                            "name": "Quarterfinals",
                            "matches": [
                                {
                                    "id": 3,
                                    "date": "2026-07-09",
                                    "lineups": { "team1": { "shorthand": "kna" }, "team2": { "name": "Fnepic" } },
                                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-82c5489c-fc06-4979-9b6a-4fd80128db96" }],
                                    "maps": [
                                        {
                                            "id": 1,
                                            "map": "nuke",
                                            "result": "13:3",
                                            "rewatches": [
                                                {
                                                    "language": "en",
                                                    "casters": ["litmus"],
                                                    "parts": [{ "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2815835154" }, "duration": "00:00:00-00:34:54" }]
                                                }
                                            ]
                                        },
                                        {
                                            "id": 2,
                                            "map": "mrg",
                                            "result": "13:2",
                                            "rewatches": [
                                                {
                                                    "language": "en",
                                                    "casters": ["litmus"],
                                                    "parts": [{ "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2815835154" }, "duration": "00:43:13-01:04:13" }]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "slug": "r2",
                            "name": "Semifinals",
                            "matches": [
                                {
                                    "id": 2,
                                    "date": "2026-07-09",
                                    "lineups": { "team1": { "shorthand": "kna" }, "team2": { "name": "Team g1do" } },
                                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-68358b26-7e44-4c35-be1c-1a3e86f2c85f" }],
                                    "maps": [
                                        {
                                            "id": 1,
                                            "map": "inf",
                                            "result": "13:6",
                                            "rewatches": [
                                                {
                                                    "language": "en",
                                                    "casters": ["litmus"],
                                                    "parts": [{ "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2815835154" }, "duration": "01:50:06-02:35:45" }]
                                                }
                                            ]
                                        },
                                        {
                                            "id": 2,
                                            "map": "mrg",
                                            "result": "13:7",
                                            "rewatches": [
                                                {
                                                    "language": "en",
                                                    "casters": ["litmus"],
                                                    "parts": [
                                                        { "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2815835154" }, "duration": "02:38:51-03:18:30" },
                                                        { "link": { "name": "Interview", "url": "https://www.twitch.tv/videos/2815835154" }, "duration": "03:24:01-03:33:06" }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "slug": "r3--grand-final",
                            "matches": [
                                {
                                    "id": 1,
                                    "name": "Grand Final",
                                    "date": "2026-07-10",
                                    "lineups": { "team1": { "name": "Team Netherlands" }, "team2": { "shorthand": "kna" } },
                                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-bb99ebe4-700b-4f79-8687-dd63ab1b0e93" }],
                                    "maps": []
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        { "slug": "s2--regional-qualifiers", "brackets": [{ "slug": "euw", "name": "Europe West" }] },
        { "slug": "s3--main-event", "duration": { "start": "2026-11-10", "end": "2026-11-15" } }
    ]
}
