=== isonovio/wyndis-archive/data/schemas/official-bracket.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name"],
    "additionalProperties": false,
    "properties": {
        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "matches": { "type": "array", "items": { "$ref": "official-match.schema.json" } },
        "note": { "type": "string" },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["transparent", "lan"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/events/2024-06-08--subzero-egames-2024.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "subzero-egames-2024",
    "name": "SubZero E-Games 2024",
    "duration": { "start": "2024-06-08", "end": "2024-06-09" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/SubZero_E-Games/2024" },
        { "name": "C.m.", "url": "https://www.challengermode.com/s/pxb/tournaments/64f4d60b-f698-45b7-9b94-08dc7fc34473" },
        { "name": "Rules", "url": "https://docs.google.com/document/d/19d6NbXlN23aTKg_mh2IiMFsoSvNXv5V-Nrt5H_wdcgA/edit" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7772/european-pro-league-female-season-1" }
    ],
    "tags": ["lan"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-2", "coach": "natosaphix" } }],
    "brackets": [
        { "slug": "s1-qualifiers" },
        {
            "slug": "s2-playoffs",
            "brackets": [
                {
                    "slug": "r1",
                    "name": "Quarterfinals",
                    "matches": [
                        {
                            "id": 2,
                            "date": "2024-06-08",
                            "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Preasy Esport" } },
                            "maps": [
                                {
                                    "id": 1,
                                    "map": "inf",
                                    "result": "7:13",
                                    "links": [{ "name": "C.m.", "url": "https://www.challengermode.com/s/pxb/games/ceaefc1f-5921-4db8-65b8-08dc8732b7e0" }]
                                },
                                {
                                    "id": 2,
                                    "map": "anb",
                                    "result": "1:13",
                                    "links": [{ "name": "C.m.", "url": "https://www.challengermode.com/s/pxb/games/feef7560-999d-4ff4-c785-08dc873a3f06" }]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
