=== isonovio/wyndis-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["impact"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/events/2022-04-09--esl-impact-cashcup-eu-2022-spring-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-spring-2",
    "name": "ESL Impact Cash Cup: Europe - Spring 2022 #2",
    "duration": { "start": "2022-04-09", "end": "2022-04-10" },
    "links": [
        { "name": "Liquipedia", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Spring/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1436" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1436" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6521/esl-impact-spring-2022-cash-cup-2-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 4,
                    "date": "2022-04-09",
                    "lineups": { "team1": { "name": "Sigma Mindset" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "d2", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16890842" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round 3",
            "matches": [
                {
                    "id": 2,
                    "date": "2022-04-09",
                    "lineups": { "team1": { "name": "Entropiq Queens" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "nuke", "result": "6:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16890931" }] }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Round 4",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-04-10",
                    "lineups": { "team1": { "name": "Nigma Galaxy" }, "team2": { "shorthand": "nsc" } },
                    "maps": [
                        { "id": 1, "map": "d2", "result": "19:17", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16891445" }] },
                        { "id": 2, "map": "vtg", "result": "16:2", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16891469" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-10-15--esl-impact-cashcup-eu-2022-autumn-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-autumn-2",
    "name": "ESL Impact Cash Cup: Europe - Autumn 2022 #2",
    "duration": { "start": "2022-10-15", "end": "2022-10-16" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Autumn/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1975" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1975" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-10-15",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "QFHAX" } },
                    "maps": [{ "id": 1, "map": "nuke", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16985700" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-10-15",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "FIFTY FIVE POWER" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16985730" }] }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-09-24--esl-impact-cashcup-eu-2022-autumn-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-autumn-1",
    "name": "ESL Impact Cash Cup: Europe - Autumn 2022 #1",
    "duration": { "start": "2022-09-24", "end": "2022-09-25" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Autumn/1" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1969" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1969" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6820/esl-impact-autumn-2022-cash-cup-1-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-09-24",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "The Elements" } },
                    "maps": [{ "id": 1, "map": "vtg", "result": "16:1", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980247" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-09-25",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "NOFEAR5" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "11:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980269" }] },
                        { "id": 2, "map": "vtg", "result": "16:6", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980291" }] },
                        { "id": 3, "map": "ovp", "result": "16:10", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980309" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-09-25",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "MostValuablePlayers" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2359189/flames-shieldmaidens-vs-mvp-esl-impact-autumn-2022-cash-cup-1-europe" }],
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "10:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980554" }] },
                        { "id": 2, "map": "nuke", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16980587" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2023-02-04--esl-impact-cashcup-eu-2023-winter-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-winter-3",
    "name": "ESL Impact Cash Cup: Europe - Winter 2023 #3",
    "duration": { "start": "2023-02-04", "end": "2023-02-05" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Winter/3" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2189" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2189" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7045/esl-impact-winter-2023-cash-cup-3-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-04",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Queend" } },
                    "maps": [{ "id": 1, "map": "mrg", "result": "16:7", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028250" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-04",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "TFW" } },
                    "maps": [
                        { "id": 1, "map": "ovp", "result": "16:3", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028282" }] },
                        { "id": 2, "map": "mrg", "result": "19:17", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028297" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-02-05",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Capybara Gay" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2361674/nip-impact-vs-capybara-esl-impact-winter-2023-cash-cup-3-europe" }],
                    "maps": [
                        { "id": 1, "map": "inf", "result": "16:11", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028424" }] },
                        { "id": 2, "map": "vtg", "result": "16:9", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17028461" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-06-04--esl-impact-cashcup-eu-2022-spring-5.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-spring-5",
    "name": "ESL Impact Cash Cup: Europe - Spring 2022 #5",
    "duration": { "start": "2022-06-04", "end": "2022-06-05" },
    "links": [
        { "name": "Liquipedia", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Spring/5" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1439" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1439" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6608/esl-impact-spring-2022-cash-cup-5-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 8,
                    "date": "2022-06-04",
                    "lineups": { "team1": { "name": "Fat Pickles" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "13:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16927718" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round 3",
            "matches": [
                {
                    "id": 4,
                    "date": "2022-06-04",
                    "lineups": { "team1": { "name": "Illusion" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "nuke", "result": "14:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16927729" }] }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Round 4",
            "matches": [
                {
                    "id": 2,
                    "date": "2022-06-05",
                    "lineups": { "team1": { "name": "Entropiq Queens" }, "team2": { "shorthand": "nsc" } },
                    "maps": [],
                    "note": "Entropiq Queens forfeited the match."
                }
            ]
        },
        {
            "slug": "r5",
            "name": "Round 5",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-05",
                    "lineups": { "team1": { "name": "NAVI Javelins" }, "team2": { "shorthand": "nsc" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2356718/navi-javelins-vs-nsc-esl-impact-spring-2022-cash-cup-5-europe" }],
                    "maps": [
                        { "id": 1, "map": "inf", "result": "12:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16928096" }] },
                        { "id": 2, "map": "nuke", "result": "16:8", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16928117" }] },
                        { "id": 3, "map": "vtg", "result": "16:12", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16928139" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-07-16--esl-impact-cashcup-eu-2022-summer-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-summer-2",
    "name": "ESL Impact Cash Cup: Europe - Summer 2022 #2",
    "duration": { "start": "2022-07-16", "end": "2022-07-17" },
    "links": [
        { "name": "Liquipedia", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Summer/2" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1626" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1626" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6668/esl-impact-summer-2022-cash-cup-2-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 8,
                    "date": "2022-07-16",
                    "lineups": { "team1": { "name": "REDraGEN Female" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "nuke", "result": "2:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944067" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round 3",
            "matches": [
                {
                    "id": 4,
                    "date": "2022-07-16",
                    "lineups": { "team1": { "name": "zlol" }, "team2": { "shorthand": "nsc" } },
                    "maps": [{ "id": 1, "map": "d2", "result": "9:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944097" }] }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "Round 4",
            "matches": [
                {
                    "id": 2,
                    "date": "2022-07-17",
                    "lineups": { "team1": { "name": "NOFEAR5" }, "team2": { "shorthand": "nsc" } },
                    "maps": [
                        { "id": 1, "map": "ovp", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944391" }] },
                        { "id": 2, "map": "vtg", "result": "3:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944400" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r5",
            "name": "Round 5",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-07-17",
                    "lineups": { "team1": { "name": "MostValuablePlayers" }, "team2": { "shorthand": "nsc" } },
                    "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2357429/mvp-vs-nsc-esl-impact-summer-2022-cash-cup-2-europe" }],
                    "maps": [
                        { "id": 1, "map": "vtg", "result": "3:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944422" }] },
                        { "id": 2, "map": "d2", "result": "1:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16944434" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-12-10--esl-impact-cashcup-eu-2022-autumn-6.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-autumn-6",
    "name": "ESL Impact Cash Cup: Europe - Autumn 2022 #6",
    "duration": { "start": "2022-12-10", "end": "2022-12-11" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Autumn/6" },
        { "name": "ESEA", "url": "https://play.esea.net/events/2085" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=2085" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "cfs", "lineup": { "roster": "cfs-2022-2", "coach": "carnem" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "R2",
            "matches": [
                {
                    "id": 5,
                    "date": "2022-12-10",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Team Lótus" } },
                    "maps": [{ "id": 1, "map": "anc", "result": "16:9", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009449" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "R3",
            "matches": [
                {
                    "id": 3,
                    "date": "2022-12-10",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Insilio Female" } },
                    "maps": [{ "id": 1, "map": "anc", "result": "16:13", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009477" }] }]
                }
            ]
        },
        {
            "slug": "r4",
            "name": "R4",
            "matches": [
                {
                    "id": 2,
                    "date": "2022-12-11",
                    "lineups": { "team1": { "shorthand": "cfs" }, "team2": { "name": "Angels" } },
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009747" }] },
                        { "id": 2, "map": "vtg", "result": "22:20", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009759" }] }
                    ]
                }
            ]
        },
        {
            "slug": "r5",
            "name": "R5",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-12-11",
                    "lineups": { "team1": { "name": "shinigami" }, "team2": { "shorthand": "cfs" } },
                    "maps": [
                        { "id": 1, "map": "anc", "result": "14:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009768" }] },
                        { "id": 2, "map": "vtg", "result": "12:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/17009783" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2020-03-16--faceit-loyalty-2020-03-16.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "faceit-loyalty-2020-03-16",
    "name": "FACEIT Loyalty Series 2020-03-16",
    "duration": { "start": "2020-03-16", "end": "2020-03-16" },
    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/championship/b27669a5-acb4-42e8-ad78-c21f37b7e709" }],
    "participants": [{ "shorthand": "twins", "lineup": { "name": "Dogsquad", "players": ["nayomy", "qiyarah"] } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 2,
                    "date": "2020-03-16",
                    "lineups": { "team1": { "shorthand": "twins" }, "team2": { "name": "kek" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-ee765b2d-4975-4b85-b264-47d882a3b64e" }],
                    "maps": [{ "id": 1, "map": "inf", "result": "16:9" }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Quarterfinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2020-03-16",
                    "lineups": { "team1": { "name": "Team K1ss0" }, "team2": { "shorthand": "twins" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-86b395c5-437f-45d1-8339-2cd960dfd31e" }],
                    "maps": [{ "id": 1, "map": "mrg", "result": "13:16" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semifinals",
            "matches": [
                {
                    "id": 1,
                    "date": "2020-03-16",
                    "lineups": { "team1": { "shorthand": "twins" }, "team2": { "name": "Green Doramio" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-89662c46-1555-430c-bfd9-ff600e145870" }],
                    "maps": [{ "id": 1, "map": "inf", "result": "12:16" }]
                }
            ]
        }
    ]
}
