=== isonovio/wyndis-archive/data/schemas/official-event.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "name", "duration", "brackets"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "name": { "type": "string" },
        "duration": { "$ref": "daterange.schema.json" },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "participants": { "type": "array", "items": { "$ref": "official-lineup.schema.json#/$defs/shorthand" } },
        "brackets": { "type": "array", "items": { "$ref": "official-bracket.schema.json" } },
        "note": { "type": "string" }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["impact"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/events/2020-10-02--faceit-loyalty-2020-10-02.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "faceit-loyalty-2020-10-02",
    "name": "FACEIT Loyalty Series 2020-10-02",
    "duration": { "start": "2020-10-02", "end": "2020-10-02" },
    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/championship/fc627396-eec8-4515-960a-f0bb82b7faca" }],
    "participants": [{ "shorthand": "nsc", "lineup": { "team": "nsc", "players": ["beauvillain", "emroott", "mrsromer", "nayomy", "qiyarah"] } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Quarterfinals",
            "matches": [
                {
                    "id": 3,
                    "date": "2020-10-02",
                    "lineups": { "team1": { "name": "Team Young-Niels" }, "team2": { "shorthand": "nsc" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-6c02608f-24b6-4ca8-ac49-4b8caf5328aa" }],
                    "maps": [{ "id": 1, "map": "inf", "result": "16:9" }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2023-07-29--esl-impact-cashcup-eu-2023-summer-3.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2023-summer-3",
    "name": "ESL Impact Cash Cup: Europe - Summer 2023 #3",
    "duration": { "start": "2023-07-29", "end": "2023-07-30" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2023/Summer/3" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/7d4a9d5b-3fe4-4f88-a128-6c5acd171ed1" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7334/esl-impact-summer-2023-cash-cup-3-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2023-2", "coach": "toh1o" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 2,
                    "date": "2023-07-29",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "YeYO" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-af23e55a-a9d1-46d9-a1a5-641f9859a20b" }],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "17:19" },
                        { "id": 2, "map": "anc", "result": "16:10" },
                        { "id": 3, "map": "mrg", "result": "16:10" }
                    ]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Grand finals",
            "matches": [
                {
                    "id": 1,
                    "date": "2023-07-29",
                    "lineups": { "team1": { "name": "NAVI Javelins" }, "team2": { "shorthand": "nipi" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/csgo/room/1-1847794f-a7d0-4d54-8f1b-a0c42bdb0e2c" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2365691/navi-javelins-vs-nip-impact-esl-impact-summer-2023-cash-cup-3-europe" }
                    ],
                    "maps": [
                        { "id": 1, "map": "nuke", "result": "16:4" },
                        { "id": 2, "map": "mrg", "result": "16:6" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2025-01-13--yalla-compass-2025-winter.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "yalla-compass-2025-winter",
    "name": "YaLLa Compass Winter 2025",
    "duration": { "start": "2025-01-13", "end": "2025-03-12" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/YaLLa_Compass/2025/Winter" },
        { "name": "Rules", "url": "https://docs.google.com/document/d/1ImgmirKL_7b6m8O6kKuCWAtukiAGMhCS0uGKu3Dmrf0/edit" }
    ],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-2", "coach": "natosaphix" } }],
    "brackets": [
        {
            "slug": "s2",
            "name": "Main Stage",
            "format": "swiss",
            "links": [{ "name": "L.p.", "url": "https://liquipedia.net/counterstrike/YaLLa_Compass/2025/Winter/Main_Stage" }],
            "brackets": [
                {
                    "slug": "r1b1",
                    "name": "Bracket 0:0",
                    "matches": [
                        {
                            "id": 2,
                            "date": "2025-02-10",
                            "lineups": { "team1": { "name": "ECLOT" }, "team2": { "shorthand": "nipi" } },
                            "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2379156/eclot-vs-nip-impact-yalla-compass-winter-2025" }],
                            "maps": [
                                { "id": 1, "map": "anc", "result": "13:1" },
                                { "id": 2, "map": "mrg", "result": "13:1" }
                            ]
                        }
                    ]
                },
                {
                    "slug": "r2b2",
                    "name": "Bracket 0:1",
                    "matches": [
                        {
                            "id": 1,
                            "date": "2025-02-18",
                            "lineups": { "team1": { "name": "Sashi" }, "team2": { "shorthand": "nipi" } },
                            "links": [{ "name": "HLTV", "url": "https://www.hltv.org/matches/2379580/sashi-vs-nip-impact-yalla-compass-winter-2025" }],
                            "maps": [
                                { "id": 1, "map": "inf", "result": "13:3" },
                                { "id": 2, "map": "mrg", "result": "13:3" }
                            ]
                        }
                    ]
                },
                {
                    "slug": "r3b3",
                    "name": "Bracket 0:2",
                    "matches": [
                        {
                            "id": 1,
                            "date": "2025-02-26",
                            "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "ESC Gaming" } },
                            "maps": [],
                            "note": "NIP Impact forfeited the match."
                        }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2024-04-06--tradeit-league-fe-masters-2.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "tradeit-league-fe-masters-2",
    "name": "Tradeit League FE Masters #2",
    "duration": { "start": "2024-04-06", "end": "2024-04-07" },
    "links": [
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/Tradeit_League/FE_Masters/2" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/d74fc0f8-f6be-430a-aa21-3a74a05c1ef1" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/7753/tradeit-league-fe-masters-season-2" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-1" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 8,
                    "date": "2024-04-06",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "Nemesis" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-cb446570-63d6-4db4-a2a7-38472396a6d0" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "13:7" },
                        { "id": 2, "map": "mrg", "result": "13:3" }
                    ]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Round of 8",
            "matches": [
                {
                    "id": 4,
                    "date": "2024-04-06",
                    "lineups": { "team1": { "name": "GUILD" }, "team2": { "shorthand": "nipi" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-095b1e83-aee6-4f23-868b-7d52890f3f45" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371164/nip-impact-vs-guild-fe-tradeit-league-fe-masters-season-2" }
                    ],
                    "maps": [
                        { "id": 1, "map": "mrg", "result": "4:13" },
                        { "id": 2, "map": "anb", "result": "13:7" },
                        { "id": 3, "map": "anc", "result": "6:13" }
                    ]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Semi-finals",
            "matches": [
                {
                    "id": 2,
                    "date": "2024-04-07",
                    "lineups": { "team1": { "name": "Fearless Cheetahs" }, "team2": { "shorthand": "nipi" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-3b863ef6-9a9e-41d7-b3a9-04edafec72d4" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371166/fearless-cheetahs-vs-nip-impact-tradeit-league-fe-masters-season-2" }
                    ],
                    "maps": [
                        {
                            "id": 1,
                            "map": "nuke",
                            "result": "5:13",
                            "rewatches": [
                                {
                                    "language": "en",
                                    "casters": ["cass"],
                                    "parts": [{ "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2113310715" }, "duration": "00:10:48-00:57:19" }]
                                }
                            ]
                        },
                        {
                            "id": 2,
                            "map": "vtg",
                            "result": "10:13",
                            "rewatches": [
                                {
                                    "language": "en",
                                    "casters": ["cass"],
                                    "parts": [{ "link": { "name": "Twitch", "url": "https://www.twitch.tv/videos/2113310715" }, "duration": "01:01:13-02:10:54" }]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "slug": "r4",
            "matches": [
                {
                    "id": 1,
                    "name": "Grand Final",
                    "date": "2024-04-07",
                    "lineups": { "team1": { "name": "Pigeons" }, "team2": { "shorthand": "nipi" } },
                    "links": [
                        { "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-7ef03d42-e212-43c3-bd99-acf200a2ec93" },
                        { "name": "HLTV", "url": "https://www.hltv.org/matches/2371167/nip-impact-vs-pigeons-tradeit-league-fe-masters-season-2" }
                    ],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "13:10" },
                        { "id": 2, "map": "vtg", "result": "13:9" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2023-04-28--iesf-friendlies-2024-w.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "iesf-friendlies-2024-w",
    "name": "IESF 2024 Women Friendlies",
    "duration": { "start": "2024-04-28", "end": "2024-04-28" },
    "tags": ["impact"],
    "participants": [{ "shorthand": "nlw", "lineup": { "team": "nlw", "players": ["maneschijnx", "missy", "nayomy", "qiyarah", "tiggz"], "coach": "natosaphix" } }],
    "brackets": [
        {
            "slug": "s1",
            "matches": [
                {
                    "id": 1,
                    "date": "2024-04-28",
                    "lineups": { "team1": { "shorthand": "nlw" }, "team2": { "name": "Belgium Women" } },
                    "maps": [{ "id": 1, "map": "unk", "result": "1:0" }]
                },
                {
                    "id": 2,
                    "date": "2024-04-28",
                    "lineups": { "team1": { "shorthand": "nlw" }, "team2": { "name": "Ukraine Women" } },
                    "maps": [{ "id": 1, "map": "unk", "result": "1:0" }]
                },
                {
                    "id": 3,
                    "date": "2024-04-28",
                    "lineups": { "team1": { "shorthand": "nlw" }, "team2": { "name": "Hungary Women" } },
                    "maps": [{ "id": 1, "map": "unk", "result": "1:0" }]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2025-04-20--iesf-friendlies-2025-w.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "iesf-friendlies-2025-w",
    "name": "IESF 2025 Women Friendlies",
    "duration": { "start": "2025-04-20", "end": "2025-04-20" },
    "tags": ["impact"],
    "participants": [{ "shorthand": "nlw", "lineup": { "roster": "nlw-2023" } }],
    "brackets": [
        {
            "slug": "s1",
            "matches": [
                {
                    "id": 1,
                    "date": "2025-04-20",
                    "lineups": { "team1": { "name": "Denmark Women" }, "team2": { "shorthand": "nlw" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-59965425-f287-43c0-8f0d-fa9ffaa689f7" }],
                    "maps": [{ "id": 1, "map": "anb", "result": "8:13" }]
                },
                {
                    "id": 1,
                    "date": "2025-04-20",
                    "lineups": { "team1": { "shorthand": "nlw" }, "team2": { "name": "Iran Women" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-a2a16119-373b-4d5f-81b4-41e7e61aac64" }],
                    "maps": [
                        { "id": 1, "map": "anc", "result": "13:1" },
                        { "id": 2, "map": "trn", "result": "13:4" }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2022-06-25--esl-impact-cashcup-eu-2022-summer-1.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2022-summer-1",
    "name": "ESL Impact Cash Cup: Europe - Summer 2022 #1",
    "duration": { "start": "2022-06-25", "end": "2022-06-26" },
    "links": [
        { "name": "Liquipedia", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/Europe/2022/Summer/1" },
        { "name": "ESEA", "url": "https://play.esea.net/events/1624" },
        { "name": "Brackets", "url": "https://play.esea.net/index.php?s=events&d=brackets&id=1624" },
        { "name": "HLTV", "url": "https://www.hltv.org/events/6635/esl-impact-summer-2022-cash-cup-1-europe" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nsc", "lineup": { "roster": "nsc-2021-2" } }],
    "brackets": [
        {
            "slug": "r1",
            "name": "Round 1",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-25",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "Pandaric Winx" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:4", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937246" }] }]
                }
            ]
        },
        {
            "slug": "r2",
            "name": "Round 2",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-25",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "FIFTYFIVEPOWER" } },
                    "maps": [{ "id": 1, "map": "ovp", "result": "16:4", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937268" }] }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round 3",
            "matches": [
                {
                    "id": 1,
                    "date": "2022-06-26",
                    "lineups": { "team1": { "shorthand": "nsc" }, "team2": { "name": "MostValuablePlayers" } },
                    "maps": [
                        { "id": 1, "map": "inf", "result": "16:14", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937300" }] },
                        { "id": 2, "map": "ovp", "result": "10:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937326" }] },
                        { "id": 3, "map": "d2", "result": "8:16", "links": [{ "name": "ESEA", "url": "https://play.esea.net/match/16937348" }] }
                    ]
                }
            ]
        }
    ]
}

=== isonovio/wyndis-archive/data/twins/events/2024-02-24--esl-impact-cashcup-eu-2024-4.json
{
    "$schema": "../../schemas/official-event.schema.json",

    "slug": "esl-impact-cashcup-eu-2024-4",
    "name": "ESL Impact Cash Cup 2024: Europe #4",
    "duration": { "start": "2024-02-24", "end": "2024-02-25" },
    "links": [
        { "name": "Liquip.", "url": "https://liquipedia.net/counterstrike/ESL/Impact_Cash_Cup/2024/Europe/4" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/championship/5e7455d9-f4ea-406b-a4f5-7f69b10714e0" }
    ],
    "tags": ["impact"],
    "participants": [{ "shorthand": "nipi", "lineup": { "roster": "nipi-2024-1" } }],
    "brackets": [
        {
            "slug": "r2",
            "name": "Round of 16",
            "matches": [
                {
                    "id": 5,
                    "date": "2024-02-24",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "gDEBbl" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-b9262b36-b30e-48ea-91b0-15974ae6e0f1" }],
                    "maps": [{ "id": 1, "map": "anc", "result": "13:11" }]
                }
            ]
        },
        {
            "slug": "r3",
            "name": "Round of 8",
            "matches": [
                {
                    "id": 3,
                    "date": "2024-02-24",
                    "lineups": { "team1": { "shorthand": "nipi" }, "team2": { "name": "more whiskey" } },
                    "links": [{ "name": "FACEIT", "url": "https://www.faceit.com/en/cs2/room/1-5e8d3011-12a2-463d-a291-bdd1a85b20d9" }],
                    "maps": [{ "id": 1, "map": "anb", "result": "9:13" }]
                }
            ]
        }
    ]
}
