=== isonovio/wyndis-archive/data/schemas/player.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname", "nationalities"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationalities": { "type": "array", "items": { "$ref": "nationality.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["twin", "ninja", "impact", "coach"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/players/mackdaddy.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "mackdaddy",
    "nickname": "MackDaddy",
    "name": "Marcus Eriksson Gonzalez",
    "nationalities": ["se"],
    "birthday": "1996-01-30",
    "tags": ["coach"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/941332" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/MackDaddy" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/19067/mackdaddy" },
        { "name": "Instagram", "url": "https://www.instagram.com/marcus.sseg" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/MackDaddy" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/MackDaddyo/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/MackDaddy0" },
        { "name": "Twitter", "url": "https://x.com/MackDaddyCS" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/rookie.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "rookie",
    "nickname": "Rookie",
    "name": "Pierre Haladjian",
    "nationalities": ["lb"],
    "tags": ["coach"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/player/11401/rookie" },
        { "name": "Twitch", "url": "https://www.twitch.tv/ro0kie_tv" },
        { "name": "Twitter", "url": "https://x.com/ro0kie_tv" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/carnem.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "carnem",
    "nickname": "CARNEM",
    "name": "Jakob Sommer",
    "nationalities": ["dk"],
    "tags": ["coach"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/coach/23139/carnem" },
        { "name": "Twitter", "url": "https://x.com/CARNEM9" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/nayay.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "nayay",
    "nickname": "nayay",
    "name": "Naja Block Bach",
    "birthday": "1998-08-27",
    "nationalities": ["dk"],
    "tags": ["impact"],
    "links": [
        { "name": "HLTV", "url": "https://www.hltv.org/player/22651/nayay" },
        { "name": "Twitter", "url": "https://x.com/nayaycs" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/eneshan.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "eneshan",
    "nickname": "eneshan",
    "name": "Eneshan Tez",
    "birthday": "2000-04-26",
    "nationalities": ["nl", "tr"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/1865450" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/eneshan" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/19066/eneshan" },
        { "name": "Instagram", "url": "https://www.instagram.com/eneshancsgo" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/Eneshan" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/eneshan1473/" },
        { "name": "TikTok", "url": "https://www.tiktok.com/@eneshancsgo" },
        { "name": "Twitch", "url": "https://www.twitch.tv/eneshancsgo" },
        { "name": "Twitter", "url": "https://x.com/eneshancsgo" },
        { "name": "YouTube", "url": "https://www.youtube.com/@eneshancsgo" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/kniven.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "kniven",
    "nickname": "kniven",
    "nationalities": [],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/kniven" },
        { "name": "Instagram", "url": "https://www.instagram.com/knivencs/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/kniven" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/regretfully/" }
    ]
}
