=== isonovio/wyndis-archive/data/schemas/player.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "type": "object",
    "required": ["slug", "nickname", "nationalities"],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "format": "uri-reference" },

        "slug": { "$ref": "slug.schema.json" },
        "nickname": { "type": "string" },
        "name": { "type": "string" },
        "birthday": { "type": "string", "format": "date" },
        "nationalities": { "type": "array", "items": { "$ref": "nationality.schema.json" } },
        "tags": { "type": "array", "items": { "$ref": "#/$defs/tag" } },
        "links": { "type": "array", "items": { "$ref": "extern-link.schema.json" } }
    },

    "$defs": {
        "tag": {
            "type": "string",
            "enum": ["twin", "ninja", "impact", "coach"]
        }
    }
}

=== isonovio/wyndis-archive/data/twins/players/aim.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "aim",
    "nickname": "aiM",
    "name": "Mia Cooper",
    "birthday": "2002-04-18",
    "nationalities": ["gb"],
    "tags": ["ninja", "impact"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/1626447" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/aiM-" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/23090/aim" },
        { "name": "Instagram", "url": "https://www.instagram.com/mia_cooper_6" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/AiM" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/aimcs2/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/aimcs_" },
        { "name": "Twitter", "url": "https://x.com/aiMCS2_" },
        { "name": "YouTube", "url": "https://www.youtube.com/@aimcsgo6" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/mariab0b.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "mariab0b",
    "nickname": "mariab0b",
    "name": "Maria Beta",
    "nationalities": ["gr", "rs"],
    "tags": ["impact"],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/mariab0b" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/25728/mariab0b" },
        { "name": "Instagram", "url": "https://www.instagram.com/mariab0b" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/mariab0b/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/mariab0b" },
        { "name": "Twitter", "url": "https://x.com/mariab0b" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/neok.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "neok",
    "nickname": "NEOK",
    "birthday": "1999-03-17",
    "nationalities": ["nl"],
    "links": [
        { "name": "NEOK", "url": "https://neokcs.com/" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/neok" },
        { "name": "Instagram", "url": "https://www.instagram.com/neokcs/" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/LeKoen" },
        { "name": "Twitch", "url": "https://www.twitch.tv/neok" },
        { "name": "Twitter", "url": "https://x.com/CsNeok" },
        { "name": "YouTube", "url": "https://www.youtube.com/neokcs" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/kd69z.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "kd69z",
    "nickname": "KD69z",
    "name": "Kais Abduljawad",
    "birthday": "1999-01-01",
    "nationalities": ["nl", "sy"],
    "links": [
        { "name": "ESEA", "url": "https://play.esea.net/users/1866730" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/KD69z" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/20800/kd69z" },
        { "name": "Instagram", "url": "https://www.instagram.com/kaisjawad_" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/KD69z" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/KD69Z/" },
        { "name": "TikTok", "url": "https://www.tiktok.com/@kd69z" },
        { "name": "Twitch", "url": "https://www.twitch.tv/kd69z" },
        { "name": "Twitter", "url": "https://x.com/KD69z_csgo" },
        { "name": "YouTube", "url": "https://www.youtube.com/@kd69z" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/pgfbailey.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "pgfbailey",
    "nickname": "pgfbailey",
    "name": "Jessica Bailey",
    "nationalities": ["be"],
    "tags": ["impact"],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/pgfbailey" },
        { "name": "Twitter", "url": "https://x.com/pgfbailey" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/olaie.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "olaie",
    "nickname": "Olaie",
    "name": "Benjamin Olaie",
    "nationalities": ["dk"],
    "birthday": "2003-02-18",
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/Olaie" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/25431/olaie" },
        { "name": "Twitch", "url": "https://www.twitch.tv/benolaie" },
        { "name": "Twitter", "url": "https://x.com/FLCOlaie" },
        { "name": "YouTube", "url": "https://www.youtube.com/@Olaie" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/d0cc.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "d0cc",
    "nickname": "D0cC",
    "name": "Shuaib Ahmad",
    "birthday": "2000-09-04",
    "nationalities": ["nl", "pk"],
    "links": [
        { "name": "d0cc", "url": "https://d0cc.gg/" },
        { "name": "ESEA", "url": "https://play.esea.net/users/D0cC%5E" },
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/D0cC" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/18361/d0cc" },
        { "name": "Instagram", "url": "https://www.instagram.com/d0cc_csgo" },
        { "name": "L.p.", "url": "https://liquipedia.net/counterstrike/D0cC" },
        { "name": "Steam", "url": "https://steamcommunity.com/id/OfficialD0cC/" },
        { "name": "Twitch", "url": "https://www.twitch.tv/d0cc_tv" },
        { "name": "Twitter", "url": "https://x.com/D0cC_csgo" },
        { "name": "YouTube", "url": "https://www.youtube.com/@D0cCTV" }
    ]
}

=== isonovio/wyndis-archive/data/twins/players/tiggz.json
{
    "$schema": "../../schemas/player.schema.json",

    "slug": "tiggz",
    "nickname": "Tiggz",
    "name": "Sabrina van Bommel",
    "nationalities": ["nl"],
    "tags": ["impact"],
    "links": [
        { "name": "FACEIT", "url": "https://www.faceit.com/en/players/Tiggzzz" },
        { "name": "HLTV", "url": "https://www.hltv.org/player/1960/tiggz" },
        { "name": "Twitter", "url": "https://x.com/tiggztv" }
    ]
}
